language: php
php:
  - 7.2
  - 7.3
  - 7.4
install:
  - travis_retry composer install --no-progress --prefer-dist
script:
  - make tests # Tests

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done # Print *.actual content
jobs:
  include:
    - env: title="Lowest Dependencies 7.2"
      php: 7.2
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - make tests

    - stage: Quality Assurance
      php: 7.4
      script:
        - make qa

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.2
      script:
        - make coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.1.0
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.2
      script:
        - composer outdated --direct
  allow_failures:
    - stage: Test Coverage
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
